sudo: required

services:
    - docker

before_install:
    - docker pull cvra/goldorak
    - docker run -v $(pwd):/home/ubuntu/catkin_ws/src cvra/goldorak /bin/bash -c "cd /home/ubuntu/catkin_ws/src/goldorak; ./build.sh"

script:
    - ./build.sh
