sudo: required

services:
    - docker

install:
    - docker pull cvra/goldorak
    - docker run -d -it --name goldorak -v $(pwd)/:/home/ubuntu/catkin_ws/src/goldorak cvra/goldorak bash

script:
    - docker exec goldorak bash -c "cd /home/ubuntu/catkin_ws/src/goldorak; ./build.sh; exit $?"
    - docker exec goldorak bash -c "cd /home/ubuntu/catkin_ws/src/goldorak; ./run_tests.sh; exit $?"
